### ISSUE TITLE
cloudflared tunnel for umbrel interface

### ISSUE THREAD

**Issue by Emilien-Lambert** [Radiokot/umbrel-cloudflared#10]
When you tunnel to an application, it works fine, but if you try to tunnel to the umbrella interface to access it from the outside, you get CSP errors. 

![image](https://github.com/user-attachments/assets/525d9aec-2e81-48e1-8ebb-541a691ec87e)

![image](https://github.com/user-attachments/assets/38c401b4-9161-4c7c-846e-4a47afd6dc1f)

It's a real shame because it's a great solution for managing other applications.

**Comment by Radiokot** [comment]
I haven't tried exposing the new Umbrel interface, and I do not recommend doing so, especially over HTTP.
More to the point, some web interfaces are simply incompatible with access over a tunnel, like those making requests to different ports. The problem is not in the tunnel connector, sorry.
