### ISSUE TITLE
Bypass app credentials

### ISSUE THREAD

**Issue by mamolas** [Radiokot/umbrel-cloudflared#11]
BTC RPC Explorer was working fine with cloudflared tunnel but in the latest update the explorer requires a custom user/pass not the Umbrel's login,
It worked previously by routing to btc-rpc-explorer_web_1:8080 from the docker-compose.yml file as per your guide, how to bypass it now to make the app public again on my custom subdomain?

Thanks

**Comment by Radiokot** [comment]
Try `http://btcpay-server_web_1:3003`

**Comment by mamolas** [comment]
> Try `http://btcpay-server_web_1:3003`

Bad gateway Error code 502
Visit [cloudflare.com](https://www.cloudflare.com/5xx-error-landing?

Also I haven't installed BTCPay server, just the node and BTC RPC Explorer

**Comment by Radiokot** [comment]
Sorry, I thought you are writing about BTCPay server.
They added auth to the web image:
https://github.com/getumbrel/umbrel-apps/blame/master/btc-rpc-explorer/docker-compose.yml#L35

Message from Umbrel about this:
>  ⚠️ A username and password is now required to access the explorer due to the new RPC Browser and RPC Terminal features. You can find your unique credentials by right-clicking on the BTC RPC Explorer app icon on the umbrelOS homescreen and selecting "Show default credentials".

So, use the credentials generated by your Umbrel for this app to access it.
