### ISSUE TITLE
can't create multiple routes

### ISSUE THREAD

**Issue by kiz8** [Radiokot/umbrel-cloudflared#3]
Due to there only being one connection string input that if modified deletes the existing route it's unclear how I can setup multiple. The walkthrough as well only shows the single route use case. Are multiple routes not supported yet?

**Comment by Radiokot** [comment]
Interesting, it is for the second time someone wants to set up multiple routes by running multiple tunnels. I think there are some misleading or outdated guides on Cloudflare Tunnel suggesting doing that, but in fact you need only one tunnel:
https://github.com/Radiokot/umbrel-cloudflared/discussions/2#discussioncomment-8182920
