### ISSUE TITLE
how to update cloudflared

### ISSUE THREAD

**Issue by owmsoton** [Radiokot/umbrel-cloudflared#8]
I'm creating a new issue to clear my doubt and how do I update the `cloudflared umbrel` which is on version `2023.10.0` and `cloudflared` is on version `2024.4.1` .

I don't have much knowledge with Docker and Umbrel in a more advanced way.  

anyway, thanks in advance for your cloudflared tunnel on umbrel.

**Comment by Radiokot** [comment]
Hi. Is version `2023.10.0` not working?
In order to update the cloudflared version, I need to test it, create a new version of the app and send it for Umbrel's approval.

**Comment by owmsoton** [comment]
First of all, my apologies for the delay in responding, your work on umbrel-cloudflared is fantastic! thank you for that.

Version 2023.10.0 is working perfectly and I'm using it to expose some services for use outside my network.

I believe that due to the way we use umbrel-cloudflared, updating to the latest version would be interesting.

Last release: [2024.6.1](https://github.com/cloudflare/cloudflared/releases/tag/2024.6.1)

**Comment by Radiokot** [comment]
Hi. I've submitted the update to Umbrel app store. If it is urgent for you, you can have it now by re-installing the app [from my store](https://github.com/Radiokot/umbrel-app-store/) or by editing the `docker-compose` file on your machine manually.

**Comment by owmsoton** [comment]
Thank you for everything.
